export enum ComplaintCategory {
  SAFETY = 'SAFETY',
  PAYMENT = 'PAYMENT',
  DRIVER_CONDUCT = 'DRIVER_CONDUCT',
  PASSENGER_CONDUCT = 'PASSENGER_CONDUCT',
  VEHICLE_CONDITION = 'VEHICLE_CONDITION',
  OTHER = 'OTHER',
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}
